[v1] Implement `createIndex` and `deleteIndex` (#67)
## Problem

Need to implement `createIndex` and `deleteIndex` on the new client
accessed from `const client = await Pinecone.createClient()`. The old
client, `const legacy = await new PineconeClient(); legacy.init()`,
should continue to work exactly as before.

These methods have the following changes from their legacy counterparts:

- [x] **Simpler arguments**. 
- For createIndex, argument has been simplified from `{ createRequest: {
name: 'foo', dimension: 256 } }` to `{ name: 'foo', dimension: 256 }`.
- For deleteIndex, argument has been simplified from `{ indexName: 'foo'
}` to `'foo'`
- [x] **Cleaned up return values.** No longer return empty string `''`
on success. The point of the `createIndex` and `deleteIndex` methods are
their side-effects (creating/deleting an index), not fetching and
displaying data. So there's no need to return anything here.
- [x] **Concise and actionable error messages.** Client-side argument
validation informs the user when they have passed argument values with
incorrect type.
- Old: `PineconeError: PineconeClient: Error calling deleteIndex:
RequiredError: Required parameter requestParameters.indexName was null
or undefined when calling deleteIndex.`
- New: `PineconeNotFoundError: Index 'baz' does not exist. Valid index
names: ['foo', 'jen-numpy-test']`
- [x] When needed, details about server-side validation errors (e.g.
invalid index name) are shown when `PineconeBadRequestError` is thrown.
- [x] Proper stacktraces 
- [x] Argument types exported


## Solution

This diff mostly follows the approach used in PR #66 to add new methods
to the client. Some small changes were made to validation methods to
improve error messaging which resulted in a lot of minor changes to
assertions about error messages created in earlier commits.

- The `buildValidator` in `validator.ts` now passes errors as complete
sentences to the onError callback. In some cases this results in
slightly longer error messages, but makes it much easier to integrate
these errors into larger messages.
- Moved some logic I wanted to reuse about building richer error
messages with the list of available indexes out of
`control/describeIndex.ts` and into a `control/utils.ts` where it could
also be accessed from `control/deleteIndex.ts`. There's some structural
similarity between these two client methods because they are both trying
to act on a single index by name.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Test Plan

- Unit tests added included in PR, integration test suite to come in
future diff
- Manual tests using `npm run repl`

### createIndex

#### createIndex: Happy path

```
> await client.createIndex({ name: 'foo', dimension: 10 })
undefined
> await client.listIndexes()
[ 'foo', 'jen-numpy-test' ]
> await client.describeIndex('foo')
{
  database: {
    name: 'foo',
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1'
  },
  status: { ready: false, state: 'Initializing' }
}
```

#### createIndex: Argument validation
```
> await client.createIndex()
Uncaught:
PineconeArgumentError: Argument to createIndex has a problem. The argument must be object.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:62:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:4:12)
    at Client.createIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:57:40)
> await client.createIndex({})
Uncaught:
PineconeArgumentError: Argument to createIndex has a problem. The argument must have required property 'name'. The argument must have required property 'dimension'.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:62:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:4:12)
    at Client.createIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:57:40)
> await client.createIndex({ name: 0, dimension: 0})
Uncaught:
PineconeArgumentError: Argument to createIndex has a problem. The property 'name' must be string. The property 'dimension' must be >= 1.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:62:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:4:12)
    at Client.createIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:57:40)
```

#### createIndex: Accepts and passes optional configuration values
```
> await client.createIndex({ name: 'bar', dimension: 10, metric: 'dotproduct', pods: 2, podType: 'p1.x2'})
undefined
> await client.describeIndex('bar')
{
  database: {
    name: 'bar',
    metric: 'dotproduct',
    pods: 2,
    replicas: 1,
    shards: 2,
    podType: 'p1.x2'
  },
  status: { ready: false, state: 'Initializing' }
}
```

#### createIndex: When validations performed on the backend fail
```
> await client.createIndex({ name: 'foo-', dimension: 10 })
Uncaught:
PineconeBadRequestError: Invalid value: "foo-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:76:59
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:33:23)
> await client.createIndex({ name: 'quux', dimension: 10, podType: 'unknown-pod-type' })
Uncaught:
PineconeBadRequestError: Unsupported value: "unknown-pod-type": supported values: "c1", "c1.x1", "c1.x2", "c1.x4", "c1.x8", "c1.x16", "c1.x32", "p1", "p1.x1", "p1.x2", "p1.x4", "p1.x8", "p2", "p2.x1", "p2.x2", "p2.x4", "p2.x8", "s1", "s1.x1", "s1.x2", "s1.x4", "s1.x8", "s1h", "s1h.x1", "s1h.x2", "s1h.x4", "s1h.x8", "s2", "s2.x1", "s2.x2", "s2.x4", "s2.x8"
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:76:59
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createIndex.js:33:23)
```

### deleteIndex

#### deleteIndex: happy path

```
> await client.listIndexes()
[ 'foo', 'jen-numpy-test' ]
> await client.deleteIndex('foo')
undefined
> await client.listIndexes()
[ 'jen-numpy-test' ]
```

#### deleteIndex: validations

```
> await client.deleteIndex()
Uncaught:
PineconeArgumentError: Argument to deleteIndex has a problem. The argument must be string.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:63:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:15:12)
    at Client.deleteIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:58:42)
```

#### deleteIndex: When requests fail (e.g. 404)

```
> await client.deleteIndex('quux')
Uncaught:
PineconeNotFoundError: Index 'quux' does not exist. Valid index names: ['foo', 'jen-numpy-test']
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:131:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:82:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteIndex.js:44:23)
```