[v1] Implement collection operations (#70)
## Problem

Similar to recent PRs #66 and #67, this PR is adding new functionality
to the revamped node client. Specifically:

- `createCollection`
- `describeCollection`
- `listCollections`
- `deleteCollection`

## Solution

More or less followed the approach used in #66 and #67 to provide
simpler arguments, runtime argument validation, and improved error
handling.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Test Plan

- Added new unit tests covering these commands.
- Manual testing with `npm run repl`

### Creating a collection

#### Validating arguments
```
> await client.createCollection()
Uncaught:
PineconeArgumentError: Argument to createCollection has a problem. The argument must be object.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:56:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:4:12)
    at Client.createCollection (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:51:40)
> await client.createCollection({})
Uncaught:
PineconeArgumentError: Argument to createCollection has a problem. The argument must have required property 'name'. The argument must have required property 'source'.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:56:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:4:12)
    at Client.createCollection (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:51:40)
> await client.createCollection({ name: 'baz-collection', source: 'baz' })
Uncaught PineconeBadRequestError: source database baz does not exist
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:88:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:33:23)
```

#### bad request

```
> await client.createCollection({ name: 'my-collection', source: 'asdf' })
Uncaught PineconeBadRequestError: source database asdf does not exist
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:88:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/createCollection.js:33:23)
```



#### happy path
```
> await client.listIndexes()
[ 'bar', 'foofoo', 'jen-numpy-test' ]
> await client.createCollection({ name: 'bar-collection', source: 'bar' })
undefined
```

### describeCollection

#### Validations

```
> await client.describeCollection()
Uncaught:
PineconeArgumentError: Argument to describeCollection has a problem. The argument must be string.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:78:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:15:12)
    at Client.describeCollection (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:73:37)
```

#### bad request
```
> await client.describeCollection('asdf')
Uncaught:
PineconeNotFoundError: Collection 'asdf' does not exist. Valid collection names: []
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:131:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:98:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeCollection.js:44:23)
````

#### happy path

```
> await client.describeCollection('bar-collection')
{ name: 'bar-collection', size: undefined, status: 'Initializing' }
> await client.describeCollection('bar-collection')
{ name: 'bar-collection', size: 3088261, status: 'Ready' }
```

### listCollection

```
> await client.listCollections()
[ 'bar-collection' ]
```

### deleteCollection

```
> await client.deleteCollection('foo-collection')
Uncaught:
PineconeNotFoundError: Collection 'foo-collection' does not exist. Valid collection names: ['bar-collection']
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:131:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteCollection.js:82:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/deleteCollection.js:44:23)
> await client.deleteCollection('bar-collection')
undefined
> await client.listCollections()
[]
>
```