[v1] Implement `describeIndex` and `listIndexes` (#66)
## Problem

Need to implement `describeIndex` and `listIndexes` on the new client
accessed from `const client = await Pinecone.createClient()`. The old
client, `const legacy = await new PineconeClient(); legacy.init()`,
should continue to work exactly as before.

`listIndexes` takes no arguments so has not significantly changed, but
`describeIndex` is significantly different. In the new client it has the
following improvements:

- [x] Expected param simplified from `{ indexName: 'my-index' }` to just
`'my-index'`
- [x] Runtime validation is performed on arguments to give feedback
before any API calls are made. This helps a lot because the underlying
generated openapi client is happy to attempt calls without doing any
validation, which often leads to confusing results and silent errors
when incorrect values are provided by the caller.
```node
// Old client: No error, but you get a nonsense response. This is a silent error that will cause problems down the line.
> await legacy.describeIndex({ indexName: '' })
{ database: undefined, status: undefined }

// New client: Tells you you're doing something wrong.
> await client.describeIndex('')
Uncaught:
PineconeArgumentError: Argument to describeIndex must NOT have fewer than 1 characters
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:20:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:99:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:15:12)
    at Client.describeIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:94:37)
    at REPL41:1:46
```

- [x] Errors are concise and actionable
- Old client: `PineconeError: PineconeClient: Error calling
describeIndex: RequiredError: Required parameter
requestParameters.indexName was null or undefined when calling
describeIndex.`
- New client: `PineconeArgumentError: Argument to describeIndex must be
string`
- [x] When errors occur, try to augment them with list of indexes
available. Saving the user a bit of effort in some cases.
- [x] Deprecated response keys with undefined values removed from
response before returning it to the caller. Makes things read much
nicer.
```node
// Old client response with legacy keys adding clutter
> await legacy.describeIndex({ indexName: 'jen-numpy-test' })
{
  database: {
    name: 'jen-numpy-test',
    dimensions: undefined,
    indexType: undefined,
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1',
    indexConfig: undefined,
    metadataConfig: undefined
  },
  status: { ready: true, state: 'Ready' }
}

// New client response, minus clutter.
> await client.describeIndex('jen-numpy-test')
{
  database: {
    name: 'jen-numpy-test',
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1'
  },
  status: { ready: true, state: 'Ready' }
}
```
Note: There's a bug in the generated openapi client causing `dimension`
not to be returned. I will tackle that in a separate PR.

### Remaining TODO on this PR
- [x] All types and errors exported for use by library users
- [x] Good coverage with unit tests
- [ ] ~~Good coverage with integration tests~~ Going to handle these
after I implement create and delete index actions since you can't list
and describe indexes if none exist.
- [ ] ~~Documentation~~ Going to tackle this in a separate PR setting up
jsdoc.

## Solution

### Error handling

Since these are the first client actions I'm implementing, a lot of
boilerplate stuff was needed to create error classes that will be reused
in other actions. Errors live in a submodule located at `src/errors/`.

The base error class `PineconeBaseError` sets up all our child error
classes to display a proper stacktrace. It also sets the prototype such
that users will be able to check what the error type was with a
statement like this:

```typescript
try {
  client.describeIndex()
} catch (e) {
  if (e instanceof PineconeAuthorizationError) {
    // ... handle auth error
  }
  // ... handle other errors
}
```

### Runtime argument validation

I did some research on different approaches to runtime validation (to
help folks using this in vanilla js contexts without the benefit of
typescript type checking). The main thing I wanted to avoid was
duplication of effort on static typechecking and runtime typechecking
since the information needed is basically the same in both places. I
also wanted something that performed well, and some popular validation
tools such as `joi` are known to be fairly slow.

I ended up pursuing a jsonSchema-based approach and added these
dependencies:
- [`typebox`](https://github.com/sinclairzx81/typebox): This provides an
expressive way to create jsonSchemas and derive Typescript types from
those same definitions. This enables us to avoid repeating the same type
information multiple times. zod is an alternative library that performs
a similar function, but overall typebox seemed to have better
documentation and about 5x more weekly downloads.
- [`ajv`](https://github.com/ajv-validator/ajv): AJV is a JSON schema
validator. I take the schema I created using typebox and then validate
the provided arguments using ajv at runtime.

These both seem like big projects with significant corporate backing.
Both MIT licensed.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Test Plan

Run `npm run repl` to access a node repl with build library already
loaded in along with my API credentials set as environment variables.

```node
> await client.describeIndex('asdf')
Uncaught:
PineconeNotFoundError: A call to https://controller.us-east1-gcp.pinecone.io/databases/asdf returned HTTP status 404. Index 'asdf' does not exist. Valid index names: ['jen-numpy-test']
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:117:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:120:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:44:23)
> await client.describeIndex('')
Uncaught:
PineconeArgumentError: Argument to describeIndex must NOT have fewer than 1 characters
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:20:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:99:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:15:12)
    at Client.describeIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:94:37)
    at REPL41:1:46
> await client.describeIndex()
Uncaught PineconeArgumentError: Argument to describeIndex must be string
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:20:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:99:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:15:12)
    at Client.describeIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:94:37)
    at REPL42:1:46
> await client.describeIndex({})
Uncaught PineconeArgumentError: Argument to describeIndex must be string
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:20:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:99:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:15:12)
    at Client.describeIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/describeIndex.js:94:37)
    at REPL43:1:46
> await client.describeIndex('jen-numpy-test')
{
  database: {
    name: 'jen-numpy-test',
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1'
  },
  status: { ready: true, state: 'Ready' }
}
```

For comparison, here are similar operations on the legacy client:

```node
> await legacy.describeIndex({ name: 'asdf' })
Uncaught:
PineconeError: PineconeClient: Error calling describeIndex: RequiredError: Required parameter requestParameters.indexName was null or undefined when calling describeIndex.
> await legacy.describeIndex({ indexName: 'asdf' })
Uncaught PineconeError: PineconeClient: Error calling describeIndex: 404: Not Found
> await legacy.describeIndex({ indexName: '' })
{ database: undefined, status: undefined }
> await legacy.describeIndex({ name: 'asdf' })
Uncaught:
PineconeError: PineconeClient: Error calling describeIndex: RequiredError: Required parameter requestParameters.indexName was null or undefined when calling describeIndex.
> await legacy.describeIndex({ })
Uncaught:
PineconeError: PineconeClient: Error calling describeIndex: RequiredError: Required parameter requestParameters.indexName was null or undefined when calling describeIndex.
> await legacy.describeIndex()
Uncaught:
PineconeError: PineconeClient: Error calling describeIndex: TypeError: Cannot read properties of undefined (reading 'indexName')
> await legacy.describeIndex({ indexName: 'jen-numpy-test' })
{
  database: {
    name: 'jen-numpy-test',
    dimensions: undefined,
    indexType: undefined,
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1',
    indexConfig: undefined,
    metadataConfig: undefined
  },
  status: { ready: true, state: 'Ready' }
}
```