[v1] Implement `configureIndex` (#68)
## Problem

Implementing `configureIndex` for the new client. Like similar PRs for
other actions, this PR adds:

- New `configureIndex` method on the client created with `const client =
await Pinecone.createClient()`
- Simplified arguments
- Runtime argument validation
- Errors with informative messages and stack traces
- Exported types for arguments and return types

## Solution

Leverage existing error mapping, validation, etc to implement new
method.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Test Plan

- Added unit tests for validation and error messages
- Manual testing with `npm run repl`

### Happy path

```
> await client.describeIndex('bar')
{
  database: {
    name: 'bar',
    metric: 'cosine',
    pods: 2,
    replicas: 2,
    shards: 1,
    podType: 'p1.x1',
    metadataConfig: { indexed: [Array] }
  },
  status: { ready: true, state: 'Ready' }
}
> await client.configureIndex('bar', { replicas: 3, podType: 'p1.x2' })
undefined
> await client.describeIndex('bar')
{
  database: {
    name: 'bar',
    metric: 'cosine',
    pods: 3,
    replicas: 3,
    shards: 1,
    podType: 'p1.x2',
    metadataConfig: { indexed: [Array] }
  },
  status: { ready: true, state: 'ScalingUpPodSize' }
}
```

### Validation failures

```
> await client.configureIndex({ replicas: 2 })
Uncaught:
PineconeArgumentError: Argument to configureIndex has a problem. The argument must be string.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:62:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Client.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:57:46)
>
> await client.configureIndex('', { replicas: 2 })
Uncaught:
PineconeArgumentError: Argument to configureIndex has a problem. The argument must not be blank.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:45:15
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:36:13
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:62:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Client.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:57:46)
> await client.configureIndex('bar', { replica: 1 })
Uncaught:
PineconeArgumentError: At least one mutable property must be specified from list ['replicas', 'podType']. Replicas must be a non-negative integer, podType must be a known pod type. See the API reference documentation at https://docs.pinecone.io/reference/configure_index
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:73:35
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Client.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:57:46)
    at REPL97:1:46
> await client.configureIndex('bar', { replicas: 0 })
Uncaught:
PineconeArgumentError: At least one mutable property must be specified from list ['replicas', 'podType']. Replicas must be a non-negative integer, podType must be a known pod type. See the API reference documentation at https://docs.pinecone.io/reference/configure_index
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:73:35
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Client.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:57:46)
    at REPL98:1:46
```

### Backend errors

#### Index not found

```
> await client.configureIndex('foo', { replicas: 2})
Uncaught:
PineconeNotFoundError: Index 'foo' does not exist. Valid index names: ['bar', 'jen-numpy-test']
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:131:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:102:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
```

#### Can't downgrade pod type

```
> await client.describeIndex('bar')
{
  database: {
    name: 'bar',
    metric: 'cosine',
    pods: 2,
    replicas: 2,
    shards: 1,
    podType: 'p1.x2',
    metadataConfig: { indexed: [Array] }
  },
  status: { ready: true, state: 'Ready' }
}
> await client.configureIndex('bar', { podType: 'p1.x1' })
Uncaught PineconeBadRequestError: scaling down pod type is not supported
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:110:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
```

#### Changing base pod type 

```
> await client.configureIndex('bar', { podType: 'asdf' })
Uncaught PineconeBadRequestError: updating base pod type is not supported
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:110:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
```

#### Quota error

```
> await client.configureIndex('bar', { replicas: 10 })
Uncaught:
PineconeBadRequestError: The index exceeds the project quota of 5 pods by 6 pods. Upgrade your account or change the project settings to increase the quota.
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:110:63
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
```