[v1] Adjust configureIndex types and fix lint warnings (#99)
## Problem

Previously, the `configureIndex` command only allowed changing either
`replicas` or `podType` but not both. The API allows changing both at
one time.

## Solution

Relax the type applied to the patch request options.

Also, fix a bunch of lint warnings that have accumulated (but which are
not related to the change in this diff).

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Test Plan

Unit tests passing.

Plus manual testing

```typescript
> await client.listIndexes()
[ { name: 'jen2' }, { name: 'jen3' }, { name: 'word-embeddings' } ]
> await client.configureIndex('word-embeddings', {})
Uncaught:
PineconeArgumentError: The second argument to configureIndex should not be empty object. Please specify at least one propert (replicas, podType) to update.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:60:31
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Pinecone.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:52:46)
    at REPL50:1:46
> await client.configureIndex('word-embeddings', { replicas: 'asdf' })
Uncaught:
PineconeArgumentError: The second argument to configureIndex had type errors: property 'replicas' must be integer.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:201:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:58:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:33:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:14:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:4:12)
    at Pinecone.configureIndex (/Users/jhamon/workspace/pinecone-ts-client/dist/control/configureIndex.js:52:46)
    at REPL51:1:46
> await client.describeIndex('word-embeddings')
{
  database: {
    name: 'word-embeddings',
    dimension: 384,
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1'
  },
  status: {
    ready: true,
    state: 'Ready',
    host: 'word-embeddings-c01b9b5.svc.us-east1-gcp.pinecone.io',
    port: 433
  }
}
> await client.configureIndex('word-embeddings', { replicas: 2, podType: 'p1.x2' })
undefined
> await client.describeIndex('word-embeddings')
{
  database: {
    name: 'word-embeddings',
    dimension: 384,
    metric: 'cosine',
    pods: 2,
    replicas: 2,
    shards: 1,
    podType: 'p1.x2'
  },
  status: {
    ready: true,
    state: 'ScalingUpPodSize',
    host: 'word-embeddings-c01b9b5.svc.us-east1-gcp.pinecone.io',
    port: 433
  }
}
```