[v1] Add query method to new client (#85)
## Problem

Need to add and expose query functionality in new client.

## Solution

By leveraging recent changes to error handling and validation, the new
code to add query is mostly just a new type definition. I should add a
couple tests in a follow-up, but there's not much new logic in here.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

`npm run repl`

#### Argument validations

Checks required stuff is there, and also that you're not passing a
non-sensical mix of id and vector params.

```
await client.index('jen2').query({})
Uncaught:
PineconeArgumentError: The argument to query accepts multiple types. Either 1) must have required properties: topK, id. 2) must have required properties: topK, vector.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:191:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:72:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:15:12)
    at Index.query (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:67:38)
    at REPL18:1:60
> await client.index('jen2').query({ id: 1, topK: 3 })
Uncaught:
PineconeArgumentError: The argument to query accepts multiple types. Either 1) had type errors: property 'id' must be string. 2) must have required property: vector.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:191:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:72:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:15:12)
    at Index.query (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:67:38)
    at REPL19:1:60
> await client.index('jen3').query({ topK: 3, vector: [0.5, 0.5, 0.5], sparseVector: { indices: [0, 1], values: [0.1, 0.25]}, id: '1' })
[
  {
    instancePath: '/vector',
    schemaPath: '#/anyOf/0/properties/vector/not',
    keyword: 'not',
    params: {},
    message: 'must NOT be valid'
  },
  {
    instancePath: '/sparseVector',
    schemaPath: '#/anyOf/0/properties/sparseVector/not',
    keyword: 'not',
    params: {},
    message: 'must NOT be valid'
  },
  {
    instancePath: '/id',
    schemaPath: '#/anyOf/1/properties/id/not',
    keyword: 'not',
    params: {},
    message: 'must NOT be valid'
  },
  {
    instancePath: '',
    schemaPath: '#/anyOf',
    keyword: 'anyOf',
    params: {},
    message: 'must match a schema in anyOf'
  }
]
Uncaught:
PineconeArgumentError: The argument to query accepts multiple types. Either 1) must not have properties: vector, sparseVector. 2) must not have property: id.
    at /Users/jhamon/workspace/pinecone-ts-client/dist/validator.js:205:19
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:72:21
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:44:23)
    at Object.next (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:25:53)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:15:12)
    at Index.query (/Users/jhamon/workspace/pinecone-ts-client/dist/data/query.js:67:38)
    at REPL3:1:60
>
```


#### Happy path

query by id, in namespace with results, including optional values and
metadata in response
```
> await client.index('jen2').namespace('foo').query({ id: '1', topK: 3, includeValues: true, includeMetadata: true })
{
  matches: [
    {
      id: '1',
      score: 1,
      values: [Array],
      sparseValues: [Object],
      metadata: [Object]
    },
    {
      id: '3',
      score: 1,
      values: [Array],
      sparseValues: [Object],
      metadata: [Object]
    },
    {
      id: '2',
      score: 1,
      values: [Array],
      sparseValues: undefined,
      metadata: undefined
    }
  ],
  namespace: 'foo'
}
>
```

query by id, in namespace with no results
```
> await client.index('jen2').namespace('bar').query({ id: '1', topK: 3, includeValues: true, includeMetadata: true })
{ matches: [], namespace: '' }
```

query by vector value,  in namespace with results
```
> await client.index('jen2').namespace('foo').query({ topK: 2, vector: [0.1] })
{
  matches: [
    {
      id: '2',
      score: 1,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    },
    {
      id: '5',
      score: 1,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    }
  ],
  namespace: 'foo'
}
```

query by vector value, in empty namespace
```
> await client.index('jen2').namespace('bar').query({ topK: 2, vector: [0.1] })
{ matches: [], namespace: 'bar' }
```

Note: At first I was suspicious that all these results have a score of
1, but I think it's an artifact of the fact the test index in these
examples only has dimension 1. I did some testing with a different index
and got more plausible looking similarity scores.

After creating a `jen3` index using the `dotproduct` metric and
dimension 3 to try out hybrid search, I saw that passing sparseVector
had an effect on the results and similarity scores.

```
> await client.index('jen3').query({ topK: 3, vector: [0.5, 0.5, 0.5] })
{
  matches: [
    {
      id: '50',
      score: 1.28853202,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    },
    {
      id: '53',
      score: 1.22128367,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    },
    {
      id: '69',
      score: 1.18652403,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    }
  ],
  namespace: ''
}

> await client.index('jen3').query({ topK: 3, vector: [0.5, 0.5, 0.5], sparseVector: { indices: [0, 1], values: [0.1, 0.25]} })
{
  matches: [
    {
      id: '50',
      score: 1.36086488,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    },
    {
      id: '53',
      score: 1.35499585,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    },
    {
      id: '20',
      score: 1.3517946,
      values: [],
      sparseValues: undefined,
      metadata: undefined
    }
  ],
  namespace: ''
}
```

#### Error cases

Vector dimension does not match index

```
> await client.index('jen2').namespace('foo').query({ topK: 10, vector: [0.1, 0.2] })
Uncaught:
PineconeBadRequestError: Query vector dimension 2 does not match the dimension of the index 1
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/utils/errorHandling.js:53:71
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/data/utils/errorHandling.js:33:23)
```

attempting a hybrid search on an index that doesn't support it

```
> await client.index('jen2').query({ topK: 4, vector: [0.25, 0.25], sparseVector: { indices: [0], values: [0.66]}  })
Uncaught PineconeBadRequestError: Index configuration does not support sparse values
    at mapHttpStatusError (/Users/jhamon/workspace/pinecone-ts-client/dist/errors/http.js:127:20)
    at /Users/jhamon/workspace/pinecone-ts-client/dist/data/utils/errorHandling.js:53:71
    at step (/Users/jhamon/workspace/pinecone-ts-client/dist/data/utils/errorHandling.js:33:23)
> await client.describeIndex('jen2')
{
  database: {
    name: 'jen2',
    dimension: 2,
    metric: 'cosine',
    pods: 1,
    replicas: 1,
    shards: 1,
    podType: 'p1.x1'
  },
  status: { ready: true, state: 'Ready' }
}
```

Known issues:
- Error message is mangled when sparseValues fields have incorrect type

Needs testing:
- Metadata filtering