[v1] Split delete functionality into deleteOne, deleteMany, and deleteAll (#86)
## Problem
Currently, the `delete` method for handling vectors is a bit overloaded.
The API accepts a variety of parameters for allowing flexibility in
deleting vectors allowing you to pass a list of `ids`, a boolean for
`deleteAll`, and a `filter` object for deleting vectors via their
metadata:

The different fields for controlling deletions have a priority on the
backend
https://github.com/pinecone-io/pinecone-db/blob/8da299373c086af48cc02cda5ace33703490cb46/pinecone-db/src/bin/replica.rs#L236.

The user may also receive errors in response if they compose the delete
with multiple fields such as `ids` with `deleteAll: true`:
https://github.com/pinecone-io/pinecone-db/blob/8da299373c086af48cc02cda5ace33703490cb46/pinecone-db/src/server/validator.rs#L100

We want to lead users into a pit of success by splitting out the delete
functionality into discrete actions which are a bit more clear.

## Solution
- Create new files under `/data/` to explicitly handle dataplane
deletion operations: `deleteOne.ts`, `deleteMany.ts`, `deleteAll.ts`.
Create explicit typebox schemas for each function to better control what
the user is able to pass in.
- Add new unit tests for each specific file to verify parameters being
sent with namespace.
- Remove the existing `delete.ts` file and functionality from the API.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan
New unit tests for covering each delete function.

### Manual Testing

`deleteAll`
```
npm run repl
await init()

// upsert vectors for testing 
await client.index('test-index').upsert([{ id: 'test-vector-1', values: [1, 2, 3] }, { id: 'test-vector-2', values: [3, 2, 1] }])

// delete all and validate
await client.index('test-index').deleteAll()

await client.index('test-index').fetch(['test-vector-1', 'test-vector2'])
{ vectors: {}, namespace: '' }
```

`deleteMany`
```
npm run repl
await init()

// upsert vectors for testing including some with different metadata structures
const vectors = [
  { id: 'test-vector-1', values: [1, 2, 3] },
  { id: 'test-vector-2', values: [3, 2, 1], metadata: { genre: 'rock' } },
  { id: 'test-vector-3', values: [2, 4, 1], metadata: { genre: 'ambient' } },
  { id: 'test-vector-4', values: [5, 1, 3], metadata: { genre: 'pop' } },
];
await client.index('test-index').upsert(vectors)

// test deleting via filter and validate
await client.index('test-index').deleteMany({ filter: { genre: 'rock' })
await client.index('test-index').fetch(['test-vector-2'])
{ vectors: {}, namespace: '' }

// test deleting via ids list and validate
await client.index('test-index').deleteMany({ ids: ['test-vector-3', 'test-vector-4'] })
await client.index('test-index').fetch(['test-vector-3', 'test-vector-4'])
{ vectors: {}, namespace: '' }

// test passing both filter and ids to make sure AJV errors out as expected
await client.index('test-index').deleteMany({ ids: ['test-vector-3', 'test-vector-4'], filter: { genre: 'ambient' } })
Uncaught:
PineconeArgumentError: The argument to deleteMany accepts multiple types. Either 1) 2)
    at /Users/austin/workspace/pinecone-ts-client/dist/validator.js:190:19
    at /Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:75:21
    at step (/Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:44:23)
    at Object.next (/Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:25:53)
    at /Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:15:12)
    at Index.deleteMany (/Users/austin/workspace/pinecone-ts-client/dist/data/deleteMany.js:70:40)
    at REPL62:1:45
```
**Note:** The above error will be fixed in a follow-up @jhamon is
working on, there should be additional info about which types are
acceptable.

`deleteOne`
```
npm run repl
await init()

// upsert vectors for testing
await client.index('test-index').upsert([{ id: '123', values: [3, 2, 1]}, { id: '321', values: [1, 2, 3]} ])

// delete a single vector and validate
await client.index('test-index').deleteOne('123')
await client.fetch('123')
{ vectors: {}, namespace: '' }
```