Update naming of Vercel token + add vercel.json  (#267)
## Problem

The latest test run of the new e2e Edge testing CI failed with the
following error:

> Error: Input required and not supplied: vercel-token
at Object.getInput
(/home/runner/work/_actions/amondnet/vercel-action/master/dist/index.js:212:15)
at
/home/runner/work/_actions/amondnet/vercel-action/master/dist/index.js:32582:26
at
/home/runner/work/_actions/amondnet/vercel-action/master/dist/index.js:32991:3
at Object.<anonymous>
(/home/runner/work/_actions/amondnet/vercel-action/master/dist/index.js:32994:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
at Module.load
(node:internal/modules/cjs/loader:[120](https://github.com/pinecone-io/pinecone-ts-client/actions/runs/10588113496/job/29340074646#step:4:133)8:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
at Function.executeUserEntryPoint [as runMain]
(node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

The first solve I think might resolve this error is to change the naming
of the Vercel token from `VERCEL_TOKEN` to `vercel-token`, as it is in
the example yamls in [the Vercel GH action's
repo](https://github.com/amondnet/vercel-action?tab=readme-ov-file#method-2---via-verceljson).

I also noticed while reading the Vercel GH action's repo that I didn't
add a `vercel.json` file, which seemingly is needed to properly deploy a
Vercel project via GH actions. So, this PR adds that as well. Info about
`vercel.json` here:
https://vercel.com/docs/projects/project-configuration#functions.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)