Handle errors in `cleanupResources` (#351)
## Problem
There's a script `utils/cleanupResources.ts` that we use to clean up
resources in the `SDK Testing` org -> `pinecone-node-client` project.
This is currently set to run on a cron nightly:

```
schedule: - cron: '0 0 * * *'
```

The process itself has been failing each day as there isn't any error
handling in the script itself when calling delete. This means any kind
of stuck index or resource fails the whole process:

```
> @pinecone-database/pinecone@6.1.2 test:integration:cleanup
> npm run build && node utils/cleanupResources.ts


> @pinecone-database/pinecone@6.1.2 build
> rm -rf dist/ && tsc

INFO Found environment variable PINECONE_API_KEY in .env file
Deleting index pod-configure-mdp2uxup
/home/runner/work/pinecone-ts-client/pinecone-ts-client/dist/errors/http.js:173
            return new PineconeBadRequestError(failedRequestInfo);
                   ^

PineconeBadRequestError: {"error":{"code":"INVALID_ARGUMENT","message":"Bad request: Cannot delete an index that is upgrading"},"status":400}
```

## Solution
- Add more graceful error handling and logging by adding a new
`safeDelete` function plus more verbose console logs.
- If an error is thrown from the top-level async process, `.catch` and
handle + exit with a proper error code.
- Clean up backups as well since they're now available through the SDK.
- Removed the testing of the `latest` TS version from our compilation
test matrix in CI. `@types/node` no longer works with the latest version
of TS, and we will need to drop support for a few 4.X versions moving
forward. We'll need to do this during the next major release since this
is a breaking change. I've added an [asana
ticket](https://app.asana.com/1/1202823119711422/project/1203260648987893/task/1211295870254059?focus=true)
to track this for now.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan
Merge + trigger workflow directly, or allow it to run later.

Tested the script directly locally:
```
> npm run build && tsx scripts/cleanupResources.ts


> @pinecone-database/pinecone@6.1.2 build
> rm -rf dist/ && tsc

INFO Found environment variable PINECONE_API_KEY in .env file

--- Cleaning up collections ---
No collections found to delete

--- Cleaning up indexes ---
Processing index test-provisioned...
✓ Successfully deleted index test-provisioned
Processing index test-index...
✓ Successfully deleted index test-index
Processing index test-index-4...
✓ Successfully deleted index test-index-4
Processing index test-index-2...
✓ Successfully deleted index test-index-2
Processing index test-index-3...
✓ Successfully deleted index test-index-3

--- Cleaning up assistants ---
No assistants found to delete

--- Cleaning up backups ---
No backups found to delete

--- Cleanup process completed ---
```


---
- To see the specific tasks where the Asana app for GitHub is being
used, see below:
  - https://app.asana.com/0/0/1210977254737392